### ISSUE TITLE
Debian stable repository gone

### ISSUE THREAD

**Issue by NodudeWasTaken** [c0re100/qBittorrent-Enhanced-Edition#231]
The debian repository used to include a stable release, its now only on unstable and testing.
Are there any plans to bring back stable?

**Comment by JaydenMcEncroe** [comment]
@Kolcha:
> due to [f022458](https://github.com/qbittorrent/qBittorrent/commit/f022458383577e1a8409b4c087c07ade84d42559) builds for Debian 10 (and other distros based on it, like Raspbian) are not possible anymore. so, no more nightly builds will be provided for these systems.
> 
> also, very likely **I'll drop whole my repo** at https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aqbittorrent-nightly&package=qbittorrent
> because I see no reasons to keep just for not stable Debian releases. but this slightly later, maybe in few months.
> 
> repo with stable releases https://software.opensuse.org//download.html?project=home%3Anikoneko%3Atest&package=qbittorrent for Debian will exist some longer time, but also I plan to drop it.

**Comment by Kolcha** [comment]
I re-added Debian stable repo for qBittorrent-Enhanced, use the same link:
https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aqbittorrent-nightly&package=qbittorrent-enhanced
packages will appear in few hours, build server under high load now

**Comment by Kolcha** [comment]
qBittorrent 4.3.4 has released with this breaking change... I thought they will include it it in at least 4.4.0... this is ridiculous
there is NO technical reason to require Qt 5.12, this is another insane limit coming from russian maintainer...
so, Debian 10 support will be for qBittorrent-Enhanced, but NOT for official qBittorrent, I'll open corresponding PR here as soon as qBittorrent-Enhanced based on 4.3.4 (or later) became available

**Comment by c0re100** [comment]
Hmmm...
I can revert this commit from enhanced repo first.
Cause that commit is not for v4.3.x...
and some v4.4 commit merged into v.4.3 :disappointed_relieved:

**Comment by Kolcha** [comment]
there is no need to revert https://github.com/qbittorrent/qBittorrent/commit/4037143f4e401ddc77a1c552c4d98986dd3bd86a, commit just drops a lot Qt version dependent code, and there is no any code that really requires Qt 5.12. this is just a limit.
it is enough to change the minimum required version to Qt 5.11, this is what is actually required now (and what Debian 10 has).
as I remember, you use cmake (and I too), so change is very simple. a lot of changes (mostly to generated configure script) are required to autotools build system.

**Comment by Kolcha** [comment]
simple change is not enough... something requires features not available in Qt 5.11:
```
[  819s] /usr/src/packages/BUILD/src/gui/properties/propertieswidget.cpp: In member function 'void PropertiesWidget::filterText(const QString&)':
[  819s] /usr/src/packages/BUILD/src/gui/properties/propertieswidget.cpp:829:22: error: 'class TorrentContentFilterModel' has no member named 'setFilterRegularExpression'; did you mean 'setFilterRegExp'?
[  819s]      m_propListModel->setFilterRegularExpression(QRegularExpression(pattern, QRegularExpression::CaseInsensitiveOption));
[  819s]                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
[  819s]                       setFilterRegExp

```
and this came with another commit... so, some work is required to get qBittorrent on Debian 10...
it's a shame  to qBittorrent developers, latest stable Debian never should be dropped, especially with 'patch' release

**Comment by Kolcha** [comment]
good news everyone! qBittorrent maintainers started discussion about Debian 10 support, and at least pointed me to commit that leads to inability to build with Qt 5.11 - https://github.com/qbittorrent/qBittorrent/commit/3b748178c21f2c2fc86b9c99a012ac3312f21a2f . reverting it fixes build.
@c0re100 just FYI. you can include this "fix" (reverting mentioned commit) into your branch

**Comment by c0re100** [comment]
> good news everyone! qBittorrent maintainers started discussion about Debian 10 support, and at least pointed me to commit that leads to inability to build with Qt 5.11 - [qbittorrent@3b74817](https://github.com/qbittorrent/qBittorrent/commit/3b748178c21f2c2fc86b9c99a012ac3312f21a2f) . reverting it fixes build.
> @c0re100 just FYI. you can include this "fix" (reverting mentioned commit) into your branch

Seems sledgehammer999 want to revert the commit 🤔

**Comment by Kolcha** [comment]
so, all required changes https://github.com/qbittorrent/qBittorrent/commit/2be30a50ef9e9ea8a80955c0d5e87c7505e6abd8 were merged into v4_3_x branch, and now it is compatible with Debian 10 packages again

**Comment by Kolcha** [comment]
4.3.4.10 is here, it is also available in [my repo](https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aqbittorrent-nightly&package=qbittorrent-enhanced) (including Debian 10), so I think this issue can be closed now. @c0re100 , please close it

**Comment by Kolcha** [comment]
Debian 10 / Raspbian 10 users, please switch to 'release' repo I added recently:
https://software.opensuse.org//download.html?project=home%3Anikoneko%3Atest&package=qbittorrent-enhanced
Debian 10 will be dropped from repo you are using ('nightly') soon
new link and comment about Debian 10 were added to readme https://github.com/c0re100/qBittorrent-Enhanced-Edition/pull/250
